### PR TITLE
IOPS-1332 MedicationDIspense.medication[x]

### PR DESCRIPTION
**Pull request by adrianhand2**
CareConnect-MedicationDispense-1 removed constraint on data type for medication. Reverting back to medication[x] enabling medication as a codeable concept and reference.

### CODE REVIEW

**Comment by martinhillyard** [comment]
@adrianhand2 can you check the description on lines 2471 and 2501. Looks like a description for an administration rather than a dispense?

**Comment by martinhillyard** [comment]
Still refers to administration of medication on line 2471

**Comment by adrianhand2** [comment]
@martinhillyard it does. I'm using the same text as used by UKCore-MedicationDispense https://simplifier.net/hl7fhirukcorer4/ukcore-medicationdispense

**Review by martinhillyard — APPROVED** [review]

**Comment by martinhillyard** [comment]
Base STU3 also has that description, so I guess it must be correct.

**Pull request merged**
